Repository kolonDT/202209_wecode_fr, pull requests merged in 2022-10, with the labels that each got.

#6 feat : 메인페이지 작업중 ++
  public/images/search.png
  src/Router.js
  src/components/DropBox.js
  src/components/EditorModal/EditorModal.js
  src/components/EditorModal/EditorModalStyle.js
  src/components/EditorModal/LinkModal.js
  src/components/MainModal/MainModal.js
  src/components/MainModal/MainModalStyle.js
  src/components/MainModal/MainModalTemplates.js
  src/components/nav/Nav.js
  src/config.js
  src/pages/editor/Editor.js
  src/pages/link/Link.js
  src/pages/main/Main.js
  src/pages/main/MainStyle.js
  src/pages/main/Template.js
  src/pages/main/TemplateList.js
  src/pages/main/TemplateStyle.js
  src/pages/user/UserSurvey.js
Labels: WIP

#12 feat : 응답자 페이지 진행중
  src/Router.js
  src/config.js
  src/pages/user/UserSurveyStyle.js
Labels: WIP

#11 Feature/editor function
  package-lock.json
  package.json
  public/data/data.json
  src/Router.js
  src/components/EditorModal/EditorModal.js
  src/components/EditorModal/EditorModalStyle.js
  src/components/Elements/LongInput.js
  src/components/Elements/MultiInput.js
  src/components/Elements/ShortInput.js
  src/components/GlobalButton.js
  src/components/GlobalInput.js
  src/components/GlobalQuestion.js
  src/components/OptionBox.js
  src/components/Questions/EmptyContainer.js
  src/components/Questions/ImageUpload.js
  src/components/Questions/LongDescription.js
  src/components/Questions/MultipleMultiple.js
  src/components/Questions/MultipleSingle.js
  src/components/Questions/PhoneInput.js
  src/components/Questions/PrivacyConsent.js
  src/components/Questions/ShortDescription.js
  src/mocks/mock.js
  src/pages/Login/Login.js
  src/pages/editor/Editor.js
  src/pages/editor/SurveyEditor.js
  src/store/store.js
Labels: mergePlz

#15 fix : 새설문지에서 삭제 기능 추가! 하지만 탬플릿에서는 안되는 상황
  public/data/2data.json
  public/data/3data.json
  public/data/4data.json
  src/components/GlobalQuestion.js
  src/components/ManagerQuestions/ImageUpload.js
  src/components/ManagerQuestions/LongDescription.js
  src/components/ManagerQuestions/MultipleMultiple.js
  src/components/ManagerQuestions/MultipleSingle.js
  src/components/ManagerQuestions/PhoneInput.js
  src/components/ManagerQuestions/PrivacyConsent.js
  src/components/ManagerQuestions/ShortDescription.js
  src/components/OptionBox.js
  src/config.js
  src/pages/editor/Editor.js
  src/pages/editor/SurveyEditor.js
Labels: mergePlz

#16 feat, fix : userPage 기본 UI 및 유효성 검사 추가 그리고 editor page 버그 발견하여 해결 전
  package-lock.json
  package.json
  public/data/3data.json
  public/data/4data.json
  src/Router.js
  src/components/DropBox.js
  src/components/EditorModal/EditorModal.js
  src/components/EditorModal/LinkModal.js
  src/components/EditorModal/LinkModalStyle.js
  src/components/EssentialBox.js
  src/components/GlobalQuestion.js
  src/components/MainModal/MainModalStyle.js
  src/components/ManagerQuestions/ImageUpload.js
  src/components/ManagerQuestions/LongDescription.js
  src/components/ManagerQuestions/MultipleMultiple.js
  src/components/ManagerQuestions/MultipleSingle.js
  src/components/ManagerQuestions/PhoneInput.js
  src/components/ManagerQuestions/PrivacyConsent.js
  src/components/ManagerQuestions/ShortDescription.js
  src/components/OptionBox.js
  src/components/UserQuestion.js
  src/components/UsersQuestions/Consent.js
  src/components/UsersQuestions/ImageShow.js
  src/components/UsersQuestions/LongDes.js
  src/components/UsersQuestions/MultipleM.js
  src/components/UsersQuestions/MultipleS.js
  src/components/UsersQuestions/Phone.js
  src/components/UsersQuestions/ShortDes.js
  src/components/nav/Nav.js
  src/config.js
  src/mocks/mock.js
  src/pages/editor/Editor.js
  src/pages/editor/SurveyEditor.js
  src/pages/link/Link.js
  src/pages/main/Main.js
  src/pages/user/UserContainer.js
  src/pages/user/UserSurvey.js
  src/store/store.js
  src/styles/theme.js
Labels: mergePlz

#14 feat : 통계 브랜치 객관식 UI 완성
  package-lock.json
  package.json
  public/data/1data.json
  public/data/1mock.json
  public/data/1mock11.json
  public/data/2data.json
  src/Router.js
  src/components/DropBox.js
  src/components/EditorModal/LinkModal.js
  src/components/MainModal/MainModal.js
  src/components/nav/Nav.js
  src/config.js
  src/pages/link/Link.js
  src/pages/main/Main.js
  src/pages/main/MainStyle.js
  src/pages/main/Template.js
  src/pages/main/TemplateList.js
  src/pages/main/TemplateStyle.js
  src/pages/statistics/Multiple.js
  src/pages/statistics/MultipleList.js
  src/pages/statistics/StatisticsPage.js
  src/pages/statistics/StatisticsStyle.js
  src/pages/statistics/Subjective.js
  src/pages/statistics/SubjectiveAnswer.js
  src/pages/statistics/SubjectiveList.js
Labels: mergePlz, WIP

#20 Fix : 전체적인 오류 수정
  .gitignore
  package-lock.json
  package.json
  src/components/FilterBox.js
  src/components/nav/Nav.js
  src/config.js
  src/pages/link/Link.js
  src/pages/main/Main.js
  src/pages/main/MainStyle.js
  src/pages/main/NoneTemplete.js
  src/pages/main/Template.js
  src/pages/main/TemplateStyle.js
  src/pages/statistics/Multiple.js
  src/pages/statistics/NonePhoneList.js
  src/pages/statistics/Phone.js
  src/pages/statistics/PhoneList.js
  src/pages/statistics/StatisticsPage.js
  src/pages/statistics/StatisticsStyle.js
  src/pages/statistics/Subjective.js
  src/pages/statistics/SubjectiveList.js
Labels: WIP
